---
- name: 'Installing YUM dependencies'
  yum:
    pkg:
      - zip
      - unzip
      - perl-DateTime
      - perl-Sys-Syslog
      - perl-LWP-Protocol-https
      - perl-Digest-SHA
    state: present
  with_items:
